name: cfn-flip
version: 0.1.0.3
github: "freckle/cfn-flip"
license: MIT
author: "Freckle R&D"
maintainer: "freckle-engineering@renaissance.com"
copyright: "2021 Renaissance Learning Inc"
category: Tools
synopsis: Haskell implementation of aws/cfn-flip
description: |
  Functions to flip between CloudFormation Yaml and JSON syntaxes

dependencies:
  - base >= 4.11 && < 10

extra-doc-files:
  - CHANGELOG.md
  - README.md

extra-source-files:
  - test/examples/*.json
  - test/examples/*.yaml

ghc-options:
  - -Weverything
  - -Wno-missing-exported-signatures # re-enables missing-signatures
  - -Wno-missing-import-lists
  - -Wno-unsafe

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

when:
  - condition: impl(ghc >= 9.2)
    ghc-options:
      - -Wno-missing-kind-signatures
  - condition: impl(ghc >= 8.10)
    ghc-options:
      - -fwrite-ide-info
      - -Wno-missing-safe-haskell-mode
      - -Wno-prepositive-qualified-module
    default-extensions:
      - DerivingVia

library:
  source-dirs: src
  dependencies:
    - aeson
    - bytestring
    - conduit
    - libyaml
    - text
    - unliftio
    - unliftio-core
    - yaml

tests:
  doctest:
    main: DocTest.hs
    dependencies:
      - aeson
      - doctest
      - yaml

  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - Glob
      - cfn-flip
      - filepath
      - hspec
      - libyaml
