name: cfn-flip
version: 0.0.0.0
dependencies:
  - base >= 4.11 && < 10

extra-source-files:
  - CHANGELOG.md
  - README.md
  - test/examples/*.json
  - test/examples/*.yaml

ghc-options:
  - -Weverything
  - -Wno-missing-exported-signatures # re-enables missing-signatures
  - -Wno-missing-import-lists
  - -Wno-unsafe

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

when:
  - condition: "impl(ghc > 8.10)"
    ghc-options:
      - -fwrite-ide-info
      - -Wno-prepositive-qualified-module
      - -Wno-missing-safe-haskell-mode
    default-extensions:
      - DerivingVia

library:
  source-dirs: src
  dependencies:
    - aeson
    - bytestring
    - conduit
    - libyaml
    - resourcet
    - rio
    - text
    - unliftio
    - yaml

tests:
  doctest:
    main: DocTest.hs
    dependencies:
      - aeson
      - doctest
      - yaml

  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - Glob
      - aeson
      - cfn-flip
      - conduit
      - filepath
      - hspec
      - libyaml
